# mandatory
name: "nmayorga092" # Your custom name (recommended: your GitHub user name)
waka name: "nmayorga092" # Your wakatime user name


# setup wakatime:
# 1: Wakatime create account: https://wakatime.com/
# 2: Install plugin in your code editor

# portfolio
# You can customize in neofetch.md
# You can change the theme by removing "console" in neofetch.md and stats.md files

# optional
# branch: You can change it in the .guthub/workflows folder (branches: [ main ])
# schedule: You can change it in the .guthub/workflows folder (cron: "0 0 * * *")