name: Waka Readme

on:
  schedule:
    # Runs at 12am CLT
    - cron: '00 04 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update the Readme
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: False
          SHOW_LINES_OF_CODE: False
          SHOW_LOC_CHART: False
          LOCALE: en
          COMMIT_MESSAGE: Updated the Readme
          SHOW_TOTAL: True
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿