name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 GMT-3
    - cron: '0 3 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: nmayorga092/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
          # COMMIT_BY_ME: "True"
          # COMMIT_MESSAGE: "Update Readme"
          